from tkinter import *

window=Tk()
window.title('one tic tac toe')

window.configure(background='#000000')
start=Label(window,text='TIC TAC TOE',font=('Times New Roman',20),fg='white',bg='black')
start.grid(column=0,row=3)

middle=Label(window,text='1st player enters X and 2nd player enters O',font=('Times New Roman',20),fg='white',bg='black')
middle.grid(column=0,row=4)
button1=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button1))
button2=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button2))
button3=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button3))
button4=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button4))
button5=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button5))
button6=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button6))
button7=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button7))
button8=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button8))
button9=Button(text='',font=('Times New Roman', 20),width=4, bg='#DAE0E2',command=lambda:update(button9))
#button10=Button(text='refresh',font=('Times New Roman', 20),width=5,fg='black',bg='white',command=refresh)
#button10.grid(column=0,row=5)
button1.grid(column=2,row=3)
button2.grid(column=3,row=3)
button3.grid(column=4,row=3)
button4.grid(column=2,row=4)
button5.grid(column=3,row=4)
button6.grid(column=4,row=4)
button7.grid(column=2,row=5)
button8.grid(column=3,row=5)
button9.grid(column=4,row=5)
window.mainloop()